config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  authenticate :user, lambda { |u| u.admin } do
    mount Sidekiq::Web => '/sidekiq'
  end
  devise_for :users, :controllers => { omniauth_callbacks: 'users/omniauth_callbacks' }
  devise_scope :user do
    get "/login" => "devise/sessions#new"
    delete "/logout" => "devise/sessions#destroy"
  end

  resources :users, only: [:show]

  resources :landing
  get "/about" => "landing#about"
  root to: "landing#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/identity.rb
class Identity < ActiveRecord::Base
  belongs_to :user
  validates_presence_of :uid, :provider
  validates_uniqueness_of :uid, :scope => :provider

  def self.find_for_oauth(auth)
    find_or_create_by(uid: auth.uid, provider: auth.provider)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :async,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable, omniauth_providers: [:google_oauth2]
         
  EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email,
            presence: true,
            uniqueness: { case_sensitive: false },
            length: { minimum: 3, maximum: 100 },
            format: { with: EMAIL_REGEX }


  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
    end
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if (data = session["devise.google_data"] && session["devise.google_data"]["extra"]["raw_info"])
        user.email = data["email"] if user.email.blank?
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  def after_sign_in_path_for(resource)
    user_path(resource.id)
  end
end

app/controllers/landing_controller.rb
class LandingController < ApplicationController
  skip_before_action :authenticate_user!
  def index
    @user = current_user
  end

  def about
    @user = current_user
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

  def google_oauth2
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user
      set_flash_message(:notice, :success, :kind => "Google") if is_navigational_format?
    else
      session["devise.google_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  def show
    @user = current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/landing_helper.rb
module LandingHelper
end

app/views/landing/index.html.erb
<div id="landing-page" class="row">
  <div id="splash" class="indigo darken-2">
    <div id="splash-container" class="section container">
      <h3 id="call-to-action">Handle Your Bills With Cryptocurrency</h2>
      <%= link_to "Learn More", about_path, class: "waves-effect waves-light btn" %>
    </div>
  </div>

  <div id="hero" class="row container section">
    <div class="col s4">
      <div class="card hoverable">
        <div class="card-content">
          <%= material_icon.credit_card.md_48 %>
          <span class="card-title">Pay Your Bills</span>
          <p>Pay your bills with cryptocurrency, no conversion necessary</p>
        </div>
      </div>
    </div>
    <div class="col s4">
      <div class="card hoverable">
        <div class="card-content">
          <%= material_icon.local_atm.md_48 %>
          <span class="card-title">Convert Paychecks</span>
          <p>Get your paychecks converted to cryptocurrency automatically</p>
        </div>
      </div>
    </div>
    <div class="col s4">
      <div class="card hoverable">
        <div class="card-content">
          <%= material_icon.autorenew.md_48 %>
          <span class="card-title">Recurring Payments</span>
          <p>Set up recurring payments quickly and easily</p>
        </div>
      </div>
    </div>
  </div>

  <div id="ico" class="row container section">
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PortalBase</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="blue darken-1">
      <div class="container">
        <div class="nav-wrapper">
          <a href="#" class="brand-logo">PortalBase</a>
          <ul id="nav-mobile" class="right hide-on-med-and-down">
            <li><%= link_to "Home", landing_index_path %></li>
            <li>
              <% if current_user.present? %>
                <%= link_to 'Sign Out', logout_path, method: :delete, id: 'sign-out' %>
              <% else %>
                <%= link_to "Log In w/Google", user_google_oauth2_omniauth_authorize_path %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    </nav>
    <main>
      <% flash.each do |message_type, message| %>
          <%= javascript_tag "Materialize.toast('#{message}', 4000)" %>
      <% end %>
      <section id="yield">
        <%= yield %>
      </section>
    </main>
  </body>
</html>

app/views/users/show.html.erb
<div class="row dashboard">
  <h1 class="center-align">Your Dashboard</h1>
  <div class="col s6">
    
  </div>
</div>